EMAIL_MARKETING_THESIS_PROJECT/Controllers/CustomerController.cs
using System.Linq;
using EMAIL_MARKETING_THESIS_PROJECT.DAL;
using EMAIL_MARKETING_THESIS_PROJECT.Models.Customer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EMAIL_MARKETING_THESIS_PROJECT.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ProjectContext context;

        public CustomerController(ProjectContext context)
        {
            this.context = context;
        }

        public IActionResult Details()
        {
            int? id = int.Parse(HttpContext.Session.GetString("UserId"));

            var customer = context.Set<Customer>().Single(c => c.Id == id);

            return View(customer);
        }
    }
}

EMAIL_MARKETING_THESIS_PROJECT/Controllers/TemplateController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using EMAIL_MARKETING_THESIS_PROJECT.Controllers.Common;
using EMAIL_MARKETING_THESIS_PROJECT.DAL;
using EMAIL_MARKETING_THESIS_PROJECT.Models.Campaigns;
using EMAIL_MARKETING_THESIS_PROJECT.Views.ViewModels.Templates;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace EMAIL_MARKETING_THESIS_PROJECT.Controllers
{
    public class TemplateController : Controller
    {
        private readonly ProjectContext context;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IToastNotification toastNotification;

        public TemplateController(ProjectContext context,
            IHostingEnvironment hostingEnvironment, IToastNotification toastNotification)
        {
            this.context = context;
            this.hostingEnvironment = hostingEnvironment;
            this.toastNotification = toastNotification;
        }

        public IActionResult Create()
        {
            var viewModel = new CreateTemplateViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateTemplateViewModel viewModel)
        {
            var uploads = Path.Combine(hostingEnvironment.WebRootPath, "uploads");
            var uniqueFileName = GetUniqueFileName(viewModel.File.FileName);
            var filePath = Path.Combine(uploads, uniqueFileName);
            var templateModel = new Template
            {
                Name = viewModel.Name,
                Content = await viewModel.File.ReadAsStringAsync()
            };

            context.Set<Template>().Add(templateModel);
            context.SaveChanges();

            await using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                await viewModel.File.CopyToAsync(fileStream);
            }

            toastNotification.AddSuccessToastMessage("Created the new template successfully.");

            return RedirectToAction("Details", new { id = templateModel.Id });
        }

        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                   + "_"
                   + Guid.NewGuid().ToString().Substring(0, 4)
                   + Path.GetExtension(fileName);
        }

        public IActionResult GetTemplates()
        {
            var templates = context.Set<Template>().ToList();
            return View(templates);
        }

        public IActionResult Details(int id)
        {
            var template = context.Set<Template>().Single(t => t.Id == id);

            return View(template);
        }

        public IActionResult Delete(int id)
        {
            try
            {
                var template = context.Set<Template>().Single(t => t.Id == id);

                context.Set<Template>().Remove(template);

                context.SaveChanges();

                toastNotification.AddSuccessToastMessage($"Deleted {template.Name} successfully.");
            }
            catch
            {
                toastNotification.AddErrorToastMessage("There was an error.");
            }

            return RedirectToAction("GetTemplates");
        }

        public IActionResult Edit(Template template)
        {
            var templateModel = context.Set<Template>().Single(m => m.Id == template.Id);

            templateModel.Name = template.Name;

            context.SaveChanges();

            toastNotification.AddSuccessToastMessage($"Edited {template.Name} successfully.");

            return RedirectToAction("Details", new { id = templateModel.Id });
        }
    }
}

EMAIL_MARKETING_THESIS_PROJECT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <style>
        body, html {
            height: 100%;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3 nav-pills nav-fill">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Campaign" asp-action="Index"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Campaign" asp-action="Create"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;New Campaign</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="MailingList" asp-action="GetMailingLists"><i class="fa fa-th-list" aria-hidden="true"></i>&nbsp;Mailing Lists</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Campaign" asp-action="Index"><i class="fa fa-magic" aria-hidden="true"></i>&nbsp;My Campaigns</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Template" asp-action="GetTemplates"><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;Email Templates</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Customer" asp-action="Details"><i class="fa fa-user" aria-hidden="true"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="LogOut"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>

    @RenderSection("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>