EMAIL_MARKETING_THESIS_PROJECT/Models/Campaigns/MailingList.cs
using EMAIL_MARKETING_THESIS_PROJECT.Models.Subscribers;
using System;
using System.Collections.Generic;

namespace EMAIL_MARKETING_THESIS_PROJECT.Models.Campaigns
{
    public class MailingList
    {
        public MailingList()
        {
            this.SubscribersLink = new List<MailingListSubscriber>();
            this.Segments = new List<Segment>();
        }

        public MailingList(string name)
        {
            this.Title = name;
            this.SubscribersLink = new List<MailingListSubscriber>();
            this.Segments = new List<Segment>();
        }

        public int Id { get; set; }

        public string Title { get; set; }

        public virtual List<MailingListSubscriber> SubscribersLink { get; set; }

        public virtual ICollection<Segment> Segments { get; set; }

        internal void Update(string title)
        {
            this.Title = title;
        }
    }
}

EMAIL_MARKETING_THESIS_PROJECT/Controllers/MailingListController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EMAIL_MARKETING_THESIS_PROJECT.DAL;
using EMAIL_MARKETING_THESIS_PROJECT.Infrastructure;
using EMAIL_MARKETING_THESIS_PROJECT.Models.Campaigns;
using EMAIL_MARKETING_THESIS_PROJECT.Models.Subscribers;
using EMAIL_MARKETING_THESIS_PROJECT.Views.ViewModels.MailingLists;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace EMAIL_MARKETING_THESIS_PROJECT.Controllers
{
    public class MailingListController : Controller
    {
        private readonly IToastNotification toastNotification;
        private readonly ProjectContext context;

        public MailingListController(ProjectContext projectContext, IToastNotification toastNotification)
        {
            this.context = projectContext;
            this.toastNotification = toastNotification;
        }

        public IActionResult GetMailingLists()
        {
            var viewModel = context.Set<MailingList>()
                .Include(m => m.SubscribersLink)
                .ToList();

            return View(viewModel);
        }

        public IActionResult Create()
        {
            var mailingList = new MailingList();

            return View(mailingList);
        }

        [HttpPost]
        public IActionResult Create(MailingList createMailingList)
        {
            var mailingList = new MailingList(createMailingList.Title);

            context.Set<MailingList>().Add(mailingList);
            context.SaveChanges();

            toastNotification.AddSuccessToastMessage($"Created new {mailingList.Title} successfully.");

            return RedirectToAction("Details", "MailingList", new { id = mailingList.Id });
        }

        public IActionResult Details(int id)
        {
            var mailingList = context.Set<MailingList>()
                .Include(m => m.SubscribersLink)
                .Single(m => m.Id == id);

            var subscribers = GetSubscribers(mailingList);

            var viewModel = new MailingListDetailsViewModel()
            {
                MailingList = mailingList,
                Subscribers = subscribers,
                AddSegmentationViewModel = new AddSegmentationViewModel
                {
                    MailingListId = mailingList.Id,
                    Areas = subscribers.GroupBy(x => x.Area).Select(x => new SelectListItem(x.Key, x.Key)).OrderBy(x => x.Value).ToArray(),
                    Cities = subscribers.GroupBy(x => x.City).Select(x => new SelectListItem(x.Key, x.Key)).OrderBy(x => x.Value).ToArray()
                },
                AddContactsViewModel = new AddContactsViewModel { MailingListId = mailingList.Id }
            };

            return View(viewModel);
        }

        private List<RFMSubscriber> GetSubscribers(MailingList mailingList)
        {
            List<RFMSubscriber> subscribers = context.Set<MailingListSubscriber>()
                .Where(ms => ms.MailingListId == mailingList.Id)
                .Select(ms => ms.Subscriber)
                .ToList();

            return subscribers;
        }

        public IActionResult Delete(int id)
        {
            var mailingList = context.Set<MailingList>().Single(m => m.Id == id);

            context.Set<MailingList>().Remove(mailingList);

            try
            {
                context.SaveChanges();

                toastNotification.AddSuccessToastMessage($"Deleted {mailingList.Title} mailing list successfully.");
            }
            catch
            {
                toastNotification.AddErrorToastMessage($"Deleted {mailingList.Title} mailing list failed.");
            }

            return RedirectToAction("GetMailingLists", "MailingList");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var mailingList = context.Set<MailingList>().Single(m => m.Id == id);

            return View(mailingList);
        }

        [HttpPost]
        public IActionResult Edit(MailingList viewModel)
        {
            var mailingList = context.Set<MailingList>().Single(m => m.Id == viewModel.Id);

            mailingList.Update(viewModel.Title);

            context.SaveChanges();

            toastNotification.AddSuccessToastMessage($"Edited the {mailingList.Title} mailing list successfully");

            return RedirectToAction("Details", "MailingList", new { id = mailingList.Id });
        }

        [HttpPost]
        public async Task<IActionResult> AddContacts(MailingListDetailsViewModel viewModel)
        {
            var mailingList = context.Set<MailingList>()
              .Include(m => m.SubscribersLink)
              .Single(m => m.Id == viewModel.AddContactsViewModel.MailingListId);

            List<RFMSubscriber> subscribers;

            if (viewModel.AddContactsViewModel.RfmModel)
            {
                var converter = ConverterFactory.CreateRFMConverter();
                var parser = ParserFactory.CreateRFMParser();
                subscribers = await AddContactsByRFMModel(viewModel.AddContactsViewModel.File, viewModel.AddContactsViewModel.Subscribers, parser, converter);
            }
            else
            {
                var converter = ConverterFactory.CreateUsualConverter();
                var parser = ParserFactory.CreateUsualParser();
                subscribers = await AddContactsAsUsual(viewModel.AddContactsViewModel.File, viewModel.AddContactsViewModel.Subscribers, parser, converter);
            }

            AddMailingListSubscribersToDb();

            context.SaveChanges();

            toastNotification.AddSuccessToastMessage("Add contacts successfully");

            return RedirectToAction("Details", new { id = mailingList.Id });

            void AddMailingListSubscribersToDb()
            {
                foreach (var mlSub in subscribers.Select(rfmSubscriber => new MailingListSubscriber
                {
                    MailingList = mailingList,
                    Subscriber = rfmSubscriber
                }))
                {
                    mailingList.SubscribersLink.Add(mlSub);
                }
            }
        }

        private async Task<List<RFMSubscriber>> AddContactsByRFMModel(IFormFile file, string subscribers, SubscriberParser parser, SystemConverter converter)
        {
            var result = new List<RFMSubscriber>();

            if (subscribers != null)
            {
                result = parser.Parse(subscribers);
            }
            else
            {
                result = await converter.Convert(file);
            }

            return result;
        }

        private async Task<List<RFMSubscriber>> AddContactsAsUsual(IFormFile file, string subscribers, SubscriberParser parser, SystemConverter converter)
        {
            var result = new List<RFMSubscriber>();

            if (subscribers != null)
            {
                result = parser.Parse(subscribers);
            }
            else
            {
                result = await converter.Convert(file);
            }

            return result;
        }

        public async Task<string> ReadFromCsvFile(Stream openReadStream)
        {
            var result = new StringBuilder();
            using (var reader = new StreamReader(openReadStream))
            {
                while (reader.Peek() >= 0)
                    result.AppendLine(await reader.ReadLineAsync());
            }
            return result.ToString();
        }

        public IActionResult EditSubscriber()
        {
            throw new NotImplementedException();
        }

        public IActionResult DeleteSubscriber(int id, int mailinglistId)
        {
            var a = context.Set<MailingListSubscriber>()
                .Single(mls => mls.SubscriberId == id && mls.MailingListId == mailinglistId);

            context.Set<MailingListSubscriber>().Remove(a);

            context.SaveChanges();

            return RedirectToAction("Details", "MailingList", new { id = mailinglistId });
        }

        [HttpGet]
        public IActionResult ViewSegments(int id)
        {
            var segments = context.Set<Segment>()
                .Include(s => s.Subscribers)
                .Include(s => s.MailingList)
                .Where(s => s.MailingList.Id == id).ToList();

            return View(segments);
        }

        public IActionResult DetailsSegment(int id)
        {
            var segment = context.Set<Segment>().Include(s => s.Subscribers).Single(s => s.Id == id);

            return View(segment);
        }

        public IActionResult DeleteSegment(int id)
        {
            var segment = context.Set<Segment>().Include(s => s.MailingList).Single(s => s.Id == id);
            context.Set<Segment>().Remove(segment);
            context.SaveChanges();

            return RedirectToAction("ViewSegments", new { id = segment.MailingList.Id });
        }

        public IActionResult DeleteAllSubscribers(int id)
        {
            var segment = context.Set<Segment>()
                .Include(s => s.MailingList)
                .Include(s => s.Subscribers)
                .Single(s => s.Id == id);

            context.Set<RFMSubscriber>().RemoveRange(segment.Subscribers);
            context.SaveChanges();

            return RedirectToAction("ViewSegments", new{id = segment.MailingList.Id} );
        }
    }
}

EMAIL_MARKETING_THESIS_PROJECT/Controllers/SegmentationController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EMAIL_MARKETING_THESIS_PROJECT.DAL;
using EMAIL_MARKETING_THESIS_PROJECT.Models.Campaigns;
using EMAIL_MARKETING_THESIS_PROJECT.Models.CustomerAnalyzers;
using EMAIL_MARKETING_THESIS_PROJECT.Models.Subscribers;
using EMAIL_MARKETING_THESIS_PROJECT.Views.ViewModels.MailingLists;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace EMAIL_MARKETING_THESIS_PROJECT.Controllers
{
    public class SegmentationController : Controller
    {
        private readonly ProjectContext context;
        private readonly Filtering filtering;
        private readonly IKmeanCustomerAnalyzer<RFMSubscriber> kmeanCustomerAnalyzer;
        private readonly IToastNotification toastNotification;

        public SegmentationController(
            ProjectContext context,
            Filtering filtering,
            IKmeanCustomerAnalyzer<RFMSubscriber> kmeanCustomerAnalyzer, IToastNotification toastNotification)
        {
            this.context = context;
            this.filtering = filtering;
            this.kmeanCustomerAnalyzer = kmeanCustomerAnalyzer;
            this.toastNotification = toastNotification;
        }

        [HttpPost]
        public async Task<IActionResult> AddSegment(MailingListDetailsViewModel viewModel)
        {
            var subscribers = context
                .Set<MailingListSubscriber>()
                .Where(mls => mls.MailingListId == viewModel.AddSegmentationViewModel.MailingListId)
                .Select(mls => mls.Subscriber).ToList();

            if (subscribers.Count == 0)
            {
                toastNotification.AddInfoToastMessage("There aren't any subscriber in this mailing list.");

                return RedirectToAction("GetMailingLists", "MailingList");
            }

            await SegmentSubscriber(viewModel.AddSegmentationViewModel, subscribers, viewModel.AddSegmentationViewModel.MailingListId);

            toastNotification.AddSuccessToastMessage($"Segmented {viewModel.AddSegmentationViewModel.NewName} successfully.");

            return RedirectToAction("ViewSegments", "MailingList", new { id = viewModel.AddSegmentationViewModel.MailingListId });
        }

        private async Task SegmentSubscriber(
            AddSegmentationViewModel viewModel,
            List<RFMSubscriber> matchedSubscribers,
            int viewModelMailingListId)
        {
            List<RFMSubscriber> subscribers;

            if (viewModel.UseRFMFiltering)
            {
                subscribers = matchedSubscribers.Any(s => (s.Frequency != null || s.Monetary != null || s.Recency != null || s.RFMClass != null))
                    ? kmeanCustomerAnalyzer.Filter(matchedSubscribers, viewModel.CriteriaViewModel, viewModel.SubscriberRateClass)
                    : new List<RFMSubscriber>();
            }
            else
            {
                subscribers = filtering.Filter(matchedSubscribers, viewModel.CriteriaViewModel);
            }

            await CreateNewMailingListWithSubscriber(viewModelMailingListId, subscribers, viewModel.NewName);
        }

        private async Task CreateNewMailingListWithSubscriber(int viewModelMailingListId,
            IEnumerable<RFMSubscriber> subscribers, string viewModelNewName)
        {
            var segment = new Segment(viewModelNewName);

            foreach (var rfmSubscriber in subscribers)
            {
                segment.Subscribers.Add(rfmSubscriber);
            }

            var mailingList = context.Set<MailingList>().Single(m => m.Id == viewModelMailingListId);
            mailingList.Segments.Add(segment);

            await context.SaveChangesAsync();
        }
    }
}

EMAIL_MARKETING_THESIS_PROJECT/Views/MailingList/Create.cshtml
@model EMAIL_MARKETING_THESIS_PROJECT.Models.Campaigns.MailingList
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Create Mailing List</h4>
<hr />
<br />
<div class="container">
    <div class="row form-group">
        <div class="col-md-6">
            @using (Html.BeginForm("Create", "MailingList", FormMethod.Post))
            {
                @Html.LabelFor(m => m.Title)
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })

                <br />

                <div>
                    <button class="btn btn-info" type="submit" class="form-control"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;Create</button>
                </div>

            }
        </div>
    </div>
</div>

EMAIL_MARKETING_THESIS_PROJECT/Views/MailingList/Details.cshtml
@using EMAIL_MARKETING_THESIS_PROJECT.Views.Common
@model EMAIL_MARKETING_THESIS_PROJECT.Views.ViewModels.MailingLists.MailingListDetailsViewModel

@functions {
    private bool HasRfmSubscribers() => Model.Subscribers.Any(s => (s.Frequency != null || s.Monetary != null || s.Recency != null));
}

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>@Model.MailingList.Title</h4>
<br />
<div>
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#addContactModal"><i class="fa fa-plus"></i>&nbsp;Add Contacts</button>
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#segmentModal"><i class="fa fa-plus"></i>&nbsp;Add Segment</button>
    <a type="button" class="btn btn-info" asp-action="ViewSegments" asp-controller="MailingList" asp-route-id="@Model.MailingList.Id"><i class="fa fa-eye"></i>&nbsp;View Segments</a>
</div>
<br />

<table class="table table-hover">
    <thead class="table-primary">
        <tr>
            <th>@Html.Label("Name")</th>
            <th>@Html.Label("Phone")</th>
            <th>@Html.Label("Email")</th>
            @if (HasRfmSubscribers())
            {
                <th>@Html.Label("Rate")</th>

            }
            <th>@Html.Label("Action")</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Subscribers)
        {
            <tr>
                <th scope="row">@item.Name</th>
                <td>@item.Phone</td>
                <td>@item.Email</td>
                @if (HasRfmSubscribers())
                {
                    <td>@item.RFMClass</td>
                }
                <td>
                    <a class="btn btn-info" asp-action="EditSubscriber" asp-controller="MailingList" asp-route-id="@item.Id" data-toggle="modal" data-target="#editMailingList"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    <a class="btn btn-info" asp-action="DeleteSubscriber" asp-controller="MailingList" asp-route-id="@item.Id" asp-route-mailinglistId="@Model.MailingList.Id"><i class="fa fa-trash" aria-hidden="true"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

@using (@Html.BeginForm("AddSegment", "Segmentation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.AddSegmentationViewModel.MailingListId)
    <div id="segmentModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Segment</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Segmentation Name: </p>
                    <div class="form-group"></div>
                    @Html.TextBoxFor(m => m.AddSegmentationViewModel.NewName, new { @class = "form-control" })

                    <hr />

                    <p>Special Filter: </p>
                    <div class="col-sm-3 form-check">
                        <input asp-for="AddSegmentationViewModel.UseRFMFiltering" class="form-check-input" data-toggle="tooltip" data-placement="top" title="If you check this, please choose at least one subscriber rate class.">
                        <label class="form-check-label">
                            RFM Filter
                        </label>
                    </div>

                    <hr />

                    <div id="kmeans-block form-group">
                        <p>Choose Subscriber Rate Class:</p>
                        @Html.DropDownListFor(m => m.AddSegmentationViewModel.SubscriberRateClass, RFMSegments.GetRFMSegments, "Please choose one...", new { @class = "form-control" })
                    </div>

                    <hr />

                    <div id="filtering-block">
                        <div class="container">
                            <p>Other Attributes</p>
                            <div class="row">
                                <div class="col-md-3 form-group">
                                    @Html.LabelFor(m => m.AddSegmentationViewModel.CriteriaViewModel.Name)
                                </div>
                                <div class="col-md-6 form-group">
                                    @Html.TextBoxFor(m => m.AddSegmentationViewModel.CriteriaViewModel.Name, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 form-group">
                                    @Html.LabelFor(m => m.AddSegmentationViewModel.CriteriaViewModel.Email)
                                </div>
                                <div class="col-md-6 form-group">
                                    @Html.TextBoxFor(m => m.AddSegmentationViewModel.CriteriaViewModel.Email, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 form-group">
                                    @Html.LabelFor(m => m.AddSegmentationViewModel.CriteriaViewModel.Age)
                                </div>
                                <div class="col-md-6 form-group">
                                    @Html.TextBoxFor(m => m.AddSegmentationViewModel.CriteriaViewModel.Age, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 form-group">
                                    @Html.LabelFor(m => m.AddSegmentationViewModel.CriteriaViewModel.Area)
                                </div>
                                <div class="col-md-6 form-group">
                                    @Html.DropDownListFor(m => m.AddSegmentationViewModel.CriteriaViewModel.Area, Model.AddSegmentationViewModel.Areas, "", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 form-group">
                                    @Html.LabelFor(m => m.AddSegmentationViewModel.CriteriaViewModel.City)
                                </div>
                                <div class="col-md-6 form-group">
                                    @Html.DropDownListFor(m => m.AddSegmentationViewModel.CriteriaViewModel.City, Model.AddSegmentationViewModel.Cities, "", new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-primary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-default btn-primary">Add Segment</button>
                </div>
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("AddContacts", "MailingList", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.AddContactsViewModel.MailingListId)
    <div id="addContactModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Contacts</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">

                    <div class="form-check">
                        <input asp-for="AddContactsViewModel.RfmModel" class="form-check-input" data-toggle="tooltip" data-placement="top" title="If you check this, please input/import subscriber string format: Name, Email, Phone, Unit Price, Recency, Frequency">
                        <label class="form-check-label">
                            RFM Model
                        </label>
                    </div>

                    <hr />

                    <div class="form-group">
                        @Html.LabelFor(m => m.AddContactsViewModel.Subscribers) (Format: Name, Email, Phone)
                        @Html.TextAreaFor(m => m.AddContactsViewModel.Subscribers, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.AddContactsViewModel.File)
                        <input asp-for="AddContactsViewModel.File" class="form-control-file" type="file" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-default">Add Contacts</button>
                </div>
            </div>
        </div>
    </div>
}

EMAIL_MARKETING_THESIS_PROJECT/Views/MailingList/DetailsSegment.cshtml
@model EMAIL_MARKETING_THESIS_PROJECT.Models.Campaigns.Segment

@{
    ViewData["Title"] = "DetailsSegment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@functions {
    private bool HasRfmSubscribers() => Model.Subscribers.Any(s => (s.Frequency != null || s.Monetary != null || s.Recency != null));
}

<h4>Segment Detail</h4>

<br />

<a class="btn btn-primary" asp-action="DeleteAllSubscribers" asp-route-id="@Model.Id"><i class="fa fa-trash" aria-hidden="true"></i>&nbsp; Delete All</a>

<br />

<table class="table table-hover">
    <thead class="table-primary">
        <tr>
            <th>@Html.Label("Name")</th>
            <th>@Html.Label("Phone")</th>
            <th>@Html.Label("Email")</th>
            @if (HasRfmSubscribers())
            {
                <th>@Html.Label("Rate")</th>

            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Subscribers)
        {
            <tr>
                <th scope="row">@item.Name</th>
                <td>@item.Phone</td>
                <td>@item.Email</td>
                @if (HasRfmSubscribers())
                {
                    <td>@item.RFMClass</td>
                }
            </tr>
        }
    </tbody>
</table>

EMAIL_MARKETING_THESIS_PROJECT/Views/MailingList/Edit.cshtml
@model EMAIL_MARKETING_THESIS_PROJECT.Models.Campaigns.MailingList

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editing Mailing List Title: @Model.Title</h1>

@using (Html.BeginForm("Edit", "MailingList", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.Title)
                    @Html.TextBoxFor(m => m.Title, new {@class = "form-control"})
                </div>
                <button type="submit" class="btn btn-info btn-sm"><i class="fa fa-edit"></i>&nbsp;Update</button>
            </div>
        </div>
    </div>
}

EMAIL_MARKETING_THESIS_PROJECT/Views/MailingList/GetMailingLists.cshtml
@model IEnumerable<EMAIL_MARKETING_THESIS_PROJECT.Models.Campaigns.MailingList>

@{
    ViewData["Title"] = "GetMailingLists";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Mailing Lists</h4>

<div>
    <a class="btn btn-info" asp-action="Create" asp-controller="MailingList"><i class="fa fa-book"></i>&nbsp;New Mailing List</a>
</div>

<br />

<table class="table table-hover">
    <thead>
        <tr class="table-primary">
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>No. of Contacts</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
           @Html.Partial("_MailingListItem", item)
        }
    </tbody>
</table>

EMAIL_MARKETING_THESIS_PROJECT/Views/MailingList/ViewSegments.cshtml
@model IEnumerable<EMAIL_MARKETING_THESIS_PROJECT.Models.Campaigns.Segment>

@{
    ViewData["Title"] = "ViewSegments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Segments</h4>

<table class="table table-hover">
    <thead class="table-primary">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                No. subscribers
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @item.Subscribers.Count
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="DetailsSegment" asp-route-id="@item.Id"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    <a class="btn btn-primary" asp-action="DeleteSegment" asp-route-id="@item.Id"><i class="fa fa-trash" aria-hidden="true"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

EMAIL_MARKETING_THESIS_PROJECT/Views/MailingList/_MailingListItem.cshtml
@model EMAIL_MARKETING_THESIS_PROJECT.Models.Campaigns.MailingList

<tr>
	<div class="well well-lg bg-light">
		<td>@Model.Title</td>
		<td>@Model.SubscribersLink.Count</td>
		<td>
			<a class="btn btn-info" asp-action="Edit" asp-controller="MailingList" asp-route-id="@Model.Id"><i class="fa fa-edit" aria-hidden="true"></i></a>
			<a class="btn btn-info" asp-action="Details" asp-controller="MailingList" asp-route-id="@Model.Id"><i class="fa fa-info-circle" aria-hidden="true"></i></a>
			<a class="btn btn-info" asp-action="Delete" asp-controller="MailingList" asp-route-id="@Model.Id"><i class="fa fa-trash" aria-hidden="true"></i></a>
		</td>
	</div>
</tr>